version: '3.8'

services:
  reportservice:
    build:
      context: .
      dockerfile: ReportService/Dockerfile
    ports:
      - "61378:61378"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://0.0.0.0:61378
    restart: unless-stopped
