version: '3.4'
services:
  ci-build:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    volumes:
      - .:/src
    working_dir: /src
    command: dotnet restore ReportService/ReportService.csproj && dotnet publish ReportService/ReportService.csproj -c Release -o ./obj/Docker/publish
